### ISSUE TITLE
Progress Data - Date Mismatch.

### ISSUE THREAD

**Issue by ruthmaben** [mapbox/report-dt#7]
@Rub21 - We are facing a concern while we spool the data for our daily Mapping scrum report.

* Dates mismatched - If we need to spool a report from 2nd - 6th of Feburary 2015,we need to select dates from 1st -7th Febuary 2015 and the dates do not match with the edits done for the previous day/week.

Please check the below screenshot - Edits done on the 2nd of Febuary 2015 are showing for the 3rd of Feburary.

![screen shot 2015-02-09 at 9 53 37 am](https://cloud.githubusercontent.com/assets/10308123/6107931/fe286ff2-b094-11e4-95d1-ce143056c246.png)

cc: @lxbarth  @shvrm @shravan91 @srividyacb @geohacker

**Comment by lxbarth** [comment]
@Rub21 - check this out, this is the problem @ruthmaben is referring to:

![](http://dl.dropboxusercontent.com/s/tpqw70ylpimurc8/Screen%20Shot%202015-02-18%20at%2011.00.25%20AM.png)

**Comment by Rub21** [comment]
@ruthmaben @lxbarth : it show correct  here :

![screenshot from 2015-02-18 10 19 02](https://cloud.githubusercontent.com/assets/1152236/6249813/bd23011a-b757-11e4-98eb-83de06a4e6b5.png)

http://rub21.github.io/report-dt/#d&2015-02-02&2015-02-08

![screenshot from 2015-02-18 10 19 35](https://cloud.githubusercontent.com/assets/1152236/6249818/c463e908-b757-11e4-9e0f-a51302a4c7a4.png)


I find out, why happen that on India time. maybe is for time. or for date picker.

**Comment by Rub21** [comment]
@ruthmaben @lxbarth : I fixed this error, for next version will be release this correction.

**Comment by shravan91** [comment]
@Rub21 - I think the problem is time and date. It still shows the wrong date in today's graph.
![error](https://cloud.githubusercontent.com/assets/3190951/6323316/c032e6aa-bb4d-11e4-98f6-f471ed29d1de.png)

cc - @lxbarth @ruthmaben

**Comment by Rub21** [comment]
@shravan91 I fixed  on my repo too. http://rub21.github.io/report-dt/#d&2015-02-16&2015-02-22
![screenshot from 2015-02-23 09 36 01](https://cloud.githubusercontent.com/assets/1152236/6329550/69f9f9b2-bb3f-11e4-9a49-1cdfc4b9bebf.png)

**Comment by shravan91** [comment]
@Rub21 - It is fixed. Thanks.

![screen shot 2015-02-24 at 4 00 50 pm](https://cloud.githubusercontent.com/assets/3190951/6347481/7228f962-bc3e-11e4-97d2-22468f26db76.png)

Closing this issue as the date mismatch function has been fixed.
cc @lxbarth @ruthmaben
